version: "3.9"

services:
  web:
    build:
      context: web
      dockerfile: Dockerfile
    volumes:
      - ./web:/stori
      - /stori/node_modules
    ports:
      - 3003:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./server:/server
  redis:
    image: redis
    ports:
      - 6379:6379
  celery-worker:
    build:
      context: server
      dockerfile: Dockerfile
    volumes:
      - ./server:/server
    command: celery -A server worker -l INFO
    depends_on:
      - redis
  celery-beat:
    build:
      context: server
      dockerfile: Dockerfile
    volumes:
      - ./server:/server
    command: celery -A server beat -l INFO
    depends_on:
      - redis


