version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/stori
      - /stori/node_modules
    ports:
      - 3003:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
