version: "3.9"

services:
  web:
    build:
      context: web
      dockerfile: Dockerfile
    volumes:
      - ./web:/stori
      - /stori/node_modules
    ports:
      - 3003:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./server:/server
