version: "3.9"

services:
  web:
    build:
      context: web
      dockerfile: Dockerfile
    volumes:
      - ./web:/stori
      - /stori/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_TINY_MCE_API_KEY=30t2v7bii9c1gspec4twqiyigi08ux6wgcfpzukg4rpiinzd
  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command: /bin/sh -c "python manage.py migrate && python manage.py runserver 0:8000"
    volumes:
      - ./server:/server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck/"]
      start_period: 10s
      interval: 30s
      timeout: 10s
      retries: 5
  redis:
    image: redis
    ports:
      - 6379:6379
  celery-worker:
    build:
      context: server
      dockerfile: Dockerfile
    volumes:
      - ./server:/server
    command: celery -A server worker -l INFO
    depends_on:
      - redis
  celery-beat:
    build:
      context: server
      dockerfile: Dockerfile
    volumes:
      - ./server:/server
    command: celery -A server beat -l INFO
    depends_on:
      redis:
        condition: service_started
      server:
        condition: service_healthy

